# Generated by Django 3.1.2 on 2020-12-11 00:07

import Tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=Tienda.models.PathAndRename('imgCategory/')),
        ),
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=Tienda.models.PathAndRename('imgProductos/')),
        ),
    ]
